#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("StayTogether.Droid.Resource", IsApplication=true)]

namespace StayTogether.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::Plugin.LocalNotifications.Resource.Drawable.plugin_lc_smallicon = global::StayTogether.Droid.Resource.Drawable.plugin_lc_smallicon;
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f080000
			public const int expire_options = 2131230720;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010003
			public const int adSize = 2130771971;
			
			// aapt resource value: 0x7f010004
			public const int adSizes = 2130771972;
			
			// aapt resource value: 0x7f010005
			public const int adUnitId = 2130771973;
			
			// aapt resource value: 0x7f010002
			public const int circleCrop = 2130771970;
			
			// aapt resource value: 0x7f010001
			public const int imageAspectRatio = 2130771969;
			
			// aapt resource value: 0x7f010000
			public const int imageAspectRatioAdjust = 2130771968;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int plugin_lc_smallicon = 2130837505;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f0a0007
			public const int List = 2131361799;
			
			// aapt resource value: 0x7f0a0008
			public const int adView = 2131361800;
			
			// aapt resource value: 0x7f0a0000
			public const int adjust_height = 2131361792;
			
			// aapt resource value: 0x7f0a0001
			public const int adjust_width = 2131361793;
			
			// aapt resource value: 0x7f0a000b
			public const int endGroup = 2131361803;
			
			// aapt resource value: 0x7f0a000d
			public const int exit = 2131361805;
			
			// aapt resource value: 0x7f0a0005
			public const int expireTime = 2131361797;
			
			// aapt resource value: 0x7f0a0004
			public const int expireTimeLabel = 2131361796;
			
			// aapt resource value: 0x7f0a0009
			public const int fragment_container = 2131361801;
			
			// aapt resource value: 0x7f0a000c
			public const int leaveGroup = 2131361804;
			
			// aapt resource value: 0x7f0a0003
			public const int mainLayout = 2131361795;
			
			// aapt resource value: 0x7f0a0006
			public const int myButton = 2131361798;
			
			// aapt resource value: 0x7f0a0002
			public const int none = 2131361794;
			
			// aapt resource value: 0x7f0a000a
			public const int settings = 2131361802;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Integer
		{
			
			// aapt resource value: 0x7f060000
			public const int google_play_services_version = 2131099648;
			
			static Integer()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Integer()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Settings = 2130903041;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f090000
			public const int SettingsMenu = 2131296256;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f05000c
			public const int Nickname_summary_preference = 2131034124;
			
			// aapt resource value: 0x7f050005
			public const int accept = 2131034117;
			
			// aapt resource value: 0x7f05000a
			public const int app_name = 2131034122;
			
			// aapt resource value: 0x7f050001
			public const int auth_google_play_services_client_facebook_display_name = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int auth_google_play_services_client_google_display_name = 2131034112;
			
			// aapt resource value: 0x7f050011
			public const int banner_ad_unit_id = 2131034129;
			
			// aapt resource value: 0x7f050002
			public const int common_google_play_services_unknown_issue = 2131034114;
			
			// aapt resource value: 0x7f050008
			public const int create_calendar_message = 2131034120;
			
			// aapt resource value: 0x7f050007
			public const int create_calendar_title = 2131034119;
			
			// aapt resource value: 0x7f050006
			public const int decline = 2131034118;
			
			// aapt resource value: 0x7f05000f
			public const int description_info = 2131034127;
			
			// aapt resource value: 0x7f050009
			public const int hello = 2131034121;
			
			// aapt resource value: 0x7f050010
			public const int menu = 2131034128;
			
			// aapt resource value: 0x7f05000d
			public const int nickname_dialog_title_preference = 2131034125;
			
			// aapt resource value: 0x7f05000b
			public const int nickname_title = 2131034123;
			
			// aapt resource value: 0x7f05000e
			public const int settings_title = 2131034126;
			
			// aapt resource value: 0x7f050004
			public const int store_picture_message = 2131034116;
			
			// aapt resource value: 0x7f050003
			public const int store_picture_title = 2131034115;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f070000
			public const int Theme_IAPTheme = 2131165184;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Xml
		{
			
			// aapt resource value: 0x7f040000
			public const int Preferences = 2130968576;
			
			static Xml()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Xml()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] AdsAttrs = new int[] {
					2130771971,
					2130771972,
					2130771973};
			
			// aapt resource value: 0
			public const int AdsAttrs_adSize = 0;
			
			// aapt resource value: 1
			public const int AdsAttrs_adSizes = 1;
			
			// aapt resource value: 2
			public const int AdsAttrs_adUnitId = 2;
			
			public static int[] LoadingImageView = new int[] {
					2130771968,
					2130771969,
					2130771970};
			
			// aapt resource value: 2
			public const int LoadingImageView_circleCrop = 2;
			
			// aapt resource value: 1
			public const int LoadingImageView_imageAspectRatio = 1;
			
			// aapt resource value: 0
			public const int LoadingImageView_imageAspectRatioAdjust = 0;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
